2VARIABLE INPUT 

CHAR ` VALUE INTRODUCER
CHAR ` VALUE TERMINATOR
     0 VALUE DELIMITER
     1 VALUE PHASE

: DELIMITER?    PHASE 0 = IF INTRODUCER ELSE TERMINATOR THEN ;
: DISPATCH      PHASE 0 = IF TYPE       ELSE EVALUATE   THEN ;
: NEXT-PHASE    PHASE 1 XOR TO PHASE DELIMITER? TO DELIMITER ;

: UNPROCESSED?  INPUT @ ;
: BOUNDARY      INPUT 2@ DELIMITER ;
: TOKEN         BOUNDARY >R 2DUP R> SCAN NIP - ;
: REMAINING     BOUNDARY SCAN DUP IF SWAP 1+ SWAP 1- THEN ;
: PROCESS       BEGIN UNPROCESSED? WHILE
                  NEXT-PHASE TOKEN DISPATCH REMAINING INPUT 2!
                REPEAT ;

: STORE-OFFSET  HERE INPUT CELL+ ! ;
: STORE-LENGTH  HERE INPUT CELL+ @ - INPUT ! ;
: READ-CHUNK    HERE 4096 STDIN READ-FILE THROW ;
: READ-CHUNKS   BEGIN READ-CHUNK ?DUP WHILE ALLOT REPEAT ;
: READ          STORE-OFFSET READ-CHUNKS STORE-LENGTH ;
